networks:
  web:
  data:

services:
  api:
    build: ./api
    image: runemortier/api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_DATABASE=labo
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web
      - data

  frontend:
    build: ./web
    image: runemortier/frontend
    expose:
      - 5000
    environment:
      - API_URL=http://api:8080
    volumes:
      - static:/app/webapp/static:ro
    networks:
      - web

  nginx:
    build: ./nginx
    image: runemortier/nginx
    ports:
      - 80:80
    volumes:
      - static:/app/static:ro
    networks:
      - web

  postgres:
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_DB=labo
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d labo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data

volumes:
  postgres:
  static: