networks:
  web:
  data:

services:
  postgres:
    image: postgres:17.0-alpine
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d labo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data

  api:
    build: ./api
    image: runemortier/api
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - web
      - data

  frontend:
    build: ./web
    image: runemortier/frontend
    expose:
      - 5000
    env_file:
      - .frontend.env
    networks:
      - web

  nginx:
    build: ./nginx
    image: runemortier/nginx
    ports:
      - 80:80
    networks:
      - web

volumes:
  postgres: